### ISSUE TITLE
Error on clicking specific Video on demand paths 

### ISSUE THREAD

**Issue by rohitraghuwanshi10** [rickeylohia/plugin.video.stalkervod#10]
When I click on specific path names while browsing the plugin fails.
Attaching logs.
[kodi.log](https://github.com/rickeylohia/plugin.video.stalkervod/files/13984304/kodi.log)

**Comment by rickeylohia** [comment]
this should be fixed in the v0.0.4
you can wait for the version to be available in the official repo (can take few days) or install manually from below
https://github.com/rickeylohia/plugin.video.stalkervod/releases/tag/v0.0.4
