### ISSUE TITLE
Long list handling and searching 

### ISSUE THREAD

**Issue by ravijot23** [rickeylohia/plugin.video.stalkervod#13]
Kindly add the ability to search and scroll through long VOD lists without the need for loading page by page. Current search function does not search the whole VOD list.

**Comment by rickeylohia** [comment]
if your portal has `All` section and if you do a search there it would search in all the VOD categories
unfortunately the whole VOD list cannot be fetched to scroll through. Currently it loads two page at a time, I can add a config to load more than two pages at a time. 
<img width="1456" alt="Screenshot 2024-03-23 at 1 28 03 PM" src="https://github.com/rickeylohia/plugin.video.stalkervod/assets/22551650/b7296029-dc28-4bb0-9c8d-01ddfee4ec9b">

**Comment by rickeylohia** [comment]
closing since not an issue but how the stalker api works

**Comment by ravijot23** [comment]
Thank you for your response. I will give it a try. Deeply appreciated.
